name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

#     - name: Build and Test Frontend
#       run: |
#         cd frontend
#         npm run build
#         npm test

#     - name: Test Backend
#       run: |
#         cd backend
#         npm test
